---
- hosts: apps

  tasks: 
    - name: Install Nginx
      apt:
        name: nginx
        state: present
      become: yes

    - name: Create local folder to save our content
      file:
        dest: /home/vagrant/static-site
        mode: 777
        state: directory


    - name: Copy configuration files
      copy: 
        src: "{{  item.src  }}"
        dest: "{{  item.dest  }}"
        owner: root
        group: root
        mode: 755
      with_items:
        - src: static_site.cfg
          dest: /etc/nginx/sites-available/static_site.cfg
        - src: ansible-logo.jpeg
          dest: /home/vagrant/static-site/ansible-logo.jpeg
        - src: index.html
          dest: /home/vagrant/static-site/index.html
      become: yes

    - name: Create symlink for the static site and the default site
      file:
        src: /etc/nginx/sites-available/static_site.cfg
        dest: /etc/nginx/sites-enabled/default
        state: link
      become: yes
      
    - name: Ensure that service is running 
      service: name=nginx state=started enabled=yes